### ISSUE TITLE
We get such a com.jcraft.jsch.JSchException: verify: false when we want to connect to an SshSession

### ISSUE THREAD

**Issue by kkrhdd** [is/jsch#25]
Hi Team,

We are getting com.jcraft.jsch.JSchException: verify: false exception Intermittently with latest version JSCH. Where it is claimed to fixed in 0.1.50. 

com.jcraft.jsch.JSchException: verify: false
	at com.jcraft.jsch.Session.connect(Session.java:307)
	at com.jcraft.jsch.Session.connect(Session.java:160)

Please have a look.

**Comment by yusong-shen** [comment]
I think this is just a mirror not the original repo, this mailing list is the right channel to reach the author https://sourceforge.net/p/jsch/mailman/

In case of `com.jcraft.jsch.JSchException: verify: false` error, it seems it is fixed in 0.1.51 not in 0.1.50.
https://stackoverflow.com/a/61923533/2943842

But you are saying latest version (0.1.55?) also have this issue, I am curious whether you have solved it now.

**Comment by kkrhdd** [comment]
@yusong-shen  Yes. I am using the latest version 0.1.55. 
I could see the fix details in http://www.jcraft.com/jsch/ChangeLog as part of 0.1.50

**Comment by kkrhdd** [comment]
@yusong-shen any update on this?

**Comment by danmaidesenling** [comment]
I am using 0.1.54, still get troubled with this issue....
